name: hangul_choseong_search
description: Choseong extraction and contiguous initial consonant search for modern Korean Hangul strings in pure Dart.
version: 0.1.0
homepage: https://github.com/beomq/hangul_choseong_search_flutter
repository: https://github.com/beomq/hangul_choseong_search_flutter
issue_tracker: https://github.com/beomq/hangul_choseong_search_flutter/issues
topics:
  - choseong
  - hangul
  - korean
  - search

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^5.0.0
  test: ^1.25.8
